### ISSUE TITLE
为什么要单独建一个led_internal_t存储内部信息

### ISSUE THREAD

**Issue by lwFlyFish** [WKJay/SignalLed#4]
代码写的非常好，但是有个疑问就是为什么会单独建一个led_internal_t的结构体
把LED的信息存储在led_internal_t或者是led_t的分组条件是什么，希望能解惑一下。

**Comment by WKJay** [comment]
我们一般在使用软件包的时候往往会包含signal_led.h头文件，而led_t是定义在头文件中的，也就是说使用者能够使用led_t中的成员，因此在led_t中定义的往往是开放给用户使用的变量或者函数，而led_internal_t是定义在源文件中，用户无法直接接触到，说明这一部分是不希望用户能够直接操作的，通过观察这个结构体也能够发现里面包含了大量的内部处理变量，如果使用者一不小心修改了就会导致运行出问题，并且在正常使用过程中往往都是越简单越好，因此将软件包内核运行所需的元素包装在一起不仅可以使对外接口变得简洁，也能够避免使用者误操作引起的运行异常。
